data<- read.table(file="./household_power_consumption.txt", header=TRUE,sep=";",na.strings="?", stringsAsFactors=FALSE)
doi<- subset(data, data$Date=="1/2/2007" | data$Date=="2/2/2007")
rm(data)
png(filename = "./plot1.png", width = 480, height = 480)
hist(doi$Global_active_power, col="red", main="Global Active Power", xlab="Global Active Power (kilowatts)")
dev.off()
